baseURL = "https://txia.ca"
title = "Tian Xia"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Assembly of trivial things"
  copyright = "Copyright Â© 2025 Tian Xia"
  dark = "off"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "research"
    name = "research"
    title = "research"
    url = "/research/"
    weight = 10

  [[menu.main]]
    identifier = "teaching"
    name = "teaching"
    title = "teaching"
    url = "/teaching/"
    weight = 10
  
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts/"
    weight = 10

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
    
[[module.mounts]]
source = 'images'
target = 'static'
    
